title = "Neni dev"
theme = "hugo-theme-shell"
languageCode = "pt-br"

[Params]
  description = "Neni's portfolio"

  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "monokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "neni"
  pcName = "laptop"
  workDir = "dev"
  profile = "profile.md"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: If you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  terminalDelay = 0

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: If you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  activityDelay = 0

  #description = """
  #Hi I am Neni!
  #Nice to meet you!

  #I’m a web programmer and I <strong>love</strong> create:
  #
  #- Systems to simplify tasks
  #- Tools to automate repetitive stuffs
  #
  #You can find me in these links:
  #
  #- <a href="https://github.com/nenitf">Github</a>
  #- <a href="https://www.linkedin.com/in/nenitf">LinkedIn</a>
  #- <a href="https://codepen.io/nenitf/collections/popular?grid_type=list">CodePen</a>
  #- <a href="https://dev.to/nenitf">Blog</a>
  #
  #"""

  # Note: If you want to use a Markdown file, you can use the following
  description = "/profile.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "portfolio"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["ISB Conecta", "https://github.com/nenitf/isb-conecta#readme"],
    ["Elefanteca", "https://github.com/nenitf/elefanteca_api#readme"],
    ["Esquecicio", "https://github.com/nenitf/esquecicio#readme"],
    ["Zombicards", "https://github.com/jooaopc/zombicards#readme"],
  ]
