title = "Neni"
languageCode = "pt-br"
description = "Neni's portfolio"

[[menus.header]]
name = "Github"
url = "https://github.com/neninja"

[[menus.header]]
name = "Linkedin"
url = "https://www.linkedin.com/in/neninja"

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.124.0"
[[module.mounts]]
    source = "node_modules/alpinejs/dist"
    target = "assets/alpinejs"
[[module.mounts]]
    source = "assets"
    target = "assets"
